### ISSUE TITLE
Document how to install a version manually

### ISSUE THREAD

**Issue by bjoale** [svendahlstrand/supervision#8]
such as 2.6.2_04

and because sitevision only provide the latest installation, one should be able to use a local file as source for the installation of a version

**Comment by svendahlstrand** [comment]
I och med att automatiskt nedladdning och installation kommer fungera när #15 är klar, och att det kanske inte är jättevanligt att installera versioner som inte SiteVision tillhandahåller längre, tänker jag mig att det manuella installationsrutinen dokumenteras bara.

**Comment by svendahlstrand** [comment]
Dokumenterat i 0bc4681bbfcd772fff5473f81550b98c000174e1.
